# theme
theme = "theme_transparent"

# config
[editor]
cursorline = false
auto-save = false
auto-format = true
auto-completion = true
idle-timeout = 1
completion-trigger-len = 1
completion-replace = true
true-color = true
bufferline = "never"
color-modes = true
rulers = [81]
mouse = true
middle-click-paste = false
line-number = "absolute"

# shell = ["C:/Program Files/Git/bin/bash.exe", "-c"]
shell = ["zsh", "-c"]

# display
[editor.statusline]
left = [
    "spacer",
    "mode",
    "spacer",
    "version-control",
    "spacer",
    "diagnostics",
]
center = [
    "file-name",
    "read-only-indicator",
    "file-modification-indicator",
    "spinner",
]
right = [
    "register",
    "selections",
    "position",
    "total-line-numbers",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "|"
skip-levels = 0

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.whitespace]
render = "all"

# keybinds
[keys.normal]
ret = "insert_newline"

[keys.normal.z]
f = ":format"

[keys.insert]
S-ret = [
    "add_newline_below",
    "move_line_down",
]
