general:
  startup_commands: ['shell-exec zebar']
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']
  config_reload_commands: ['shell-exec zebar']
    
  focus_follows_cursor: false
  toggle_workspace_on_refocus: false

  cursor_jump:
    enabled: true
    # options: 'monitor_focus', 'window_focus'
    trigger: 'window_focus'

gaps:
  scale_with_dpi: true
  inner_gap: '0px'
  outer_gap:
    top: '40px'
    right: '0px'
    bottom: '0px'
    left: '0px'

window_effects:
  focused_window:
    border:
      enabled: true
      color: '#0be007'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      # options: 'square', 'rounded', 'small_rounded'
      style: 'square'
  other_windows:
    border:
      enabled: true
      color: '#616161'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: 'square'

window_behavior:
  # options: 'tiling', 'floating'
  initial_state: 'tiling'
  state_defaults:
    floating:
      centered: true
      shown_on_top: false
    fullscreen:
      maximized: true
      shown_on_top: false

workspaces:
  - name: '1'
  - name: '2'
  - name: '3'

window_rules:
  - commands: ['ignore']
    match:
      # System-wide
      - window_process: { equals: 'zebar' }
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }

      # App-specific
      - window_process: { equals: 'regedit' }
      - window_process: { equals: 'cs2' }
      - window_process: { equals: 'ClickShare' }
      - window_process: { equals: 'PresentSense' }
      - window_process: { equals: 'clickshare_native' }

binding_modes:
  - name: 'pause'
    keybindings:
      - commands: ['wm-disable-binding-mode --name pause']
        bindings: ['alt+shift+p']

keybindings:
  # Shift focus
  - commands: ['focus --direction left']
    bindings: ['alt+h']
  - commands: ['focus --direction right']
    bindings: ['alt+l']
  - commands: ['focus --direction up']
    bindings: ['alt+k']
  - commands: ['focus --direction down']
    bindings: ['alt+j']

  # Move focused window
  - commands: ['move --direction left']
    bindings: ['alt+shift+h']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l']
  - commands: ['move --direction up']
    bindings: ['alt+shift+k']
  - commands: ['move --direction down']
    bindings: ['alt+shift+j']

  # Resize focused window
  - commands: ['resize --width -4%']
    bindings: ['alt+u']
  - commands: ['resize --width +4%']
    bindings: ['alt+p']
  - commands: ['resize --height +4%']
    bindings: ['alt+o']
  - commands: ['resize --height -4%']
    bindings: ['alt+i']

  # Tiling
  - commands: ['wm-enable-binding-mode --name pause']
    bindings: ['alt+shift+p']
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']

  # Minimize/maximize/close
  - commands: ['toggle-fullscreen']
    bindings: ['alt+shift+m']
  - commands: ['set-minimized']
    bindings: ['alt+m']
  - commands: ['close']
    bindings: ['alt+q']

  # WM commands
  - commands: ['wm-exit']
    bindings: ['alt+shift+e']
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+r']
  - commands: ['wm-redraw']
    bindings: ['alt+shift+t']

  # Focus workspace
  - commands: ['focus --workspace 1']
    bindings: ['alt+1']
  - commands: ['focus --workspace 2']
    bindings: ['alt+2']
  - commands: ['focus --workspace 3']
    bindings: ['alt+3']

  # Move to workspace
  - commands: ['move --workspace 1']
    bindings: ['alt+shift+1']
  - commands: ['move --workspace 2']
    bindings: ['alt+shift+2']
  - commands: ['move --workspace 3']
    bindings: ['alt+shift+3']
    
  # Move workspace
  - commands: ['move-workspace --direction left']
    bindings: ['alt+shift+left']
  - commands: ['move-workspace --direction right']
    bindings: ['alt+shift+right']
  - commands: ['move-workspace --direction up']
    bindings: ['alt+shift+up']
  - commands: ['move-workspace --direction down']
    bindings: ['alt+shift+down']

  # System execs
  - commands: ['shell-exec wt']
    bindings: ['alt+enter']
  - commands: ['shell-exec explorer']
    bindings: ['alt+shift+enter']
  - commands: ['shell-exec hx']
    bindings: ["alt+shift+n"]
  - commands: ["shell-exec Z:/Peripherals\ +\ software/software/win/restartexplorer.bat"]
    bindings: ['alt+r']

  # App execs
  - commands: ["shell-exec %localappdata%/Programs/Microsoft VS Code/Code.exe"]
    bindings: ['alt+c']
  - commands: ["shell-exec %appdata%/Spotify/Spotify.exe"]
    bindings: ['alt+s']
  - commands: ["shell-exec %programfiles%/Mozilla Firefox/firefox.exe"]
    bindings: ['alt+f']
  - commands: ["shell-exec %programfiles%/Mozilla Firefox/private_browsing.exe"]
    bindings: ['alt+n']
  - commands: ["shell-exec %programfiles(x86)%/Steam/steam.exe"]
    bindings: ['alt+a']
  - commands: ["shell-exec %localappdata%/Discord/Discord.lnk"]
    bindings: ['alt+d']
  - commands: ["shell-exec %programfiles(x86)%/ProtonVPN/ProtonVPN.exe"]
    bindings: ['alt+z']
