general:
  focus_follows_cursor: false
  cursor_follows_focus: true
  toggle_workspace_on_refocus: false
  show_floating_on_top: true
  floating_window_move_amount: "5%"
  center_new_floating_windows: true
  window_animations: false

gaps:
  inner_gap: "5px"
  outer_gap: "8px"

focus_borders:
  active:
    enabled: true
    color: "#efefef"
  inactive:
    enabled: false
    color: "#000000"

bar:
  enabled: true
  height: "30px"
  position: "top"
  opacity: 0.7
  background: "#2b2a33"
  foreground: "#eeeeee"
  font_family: "Inconsolata"
  font_size: "13px"
  font_weight: 400
  padding: "4px 6px"
  offset_x: 0
  offset_y: 0
  border_radius: 0
  component_separator:
    label: " "
  components_left:
    - type: "clock"
      time_formatting: "HH:mm:ss ddd MMM dd" 
    - type: "weather"
  components_center:
    - type: "music"
      label_not_playing: ""
      label_paused: "{song_title}"
      label_playing: "{song_title}"
      max_title_length: 30
    - type: "workspaces"
      foreground: "#ffffff"
      focused_workspace_background: "#636363"
      default_workspace_background: "transparent"
    - type: "window title"
  components_right:
    - type: "network"
      label_no_internet: "NC"
      label_ethernet: "Eth"
      label_wifi_strength_0: "WiFi: 0%"
      label_wifi_strength_25: "WiFi: 25%"
      label_wifi_strength_50: "WiFi: 50%"
      label_wifi_strength_75: "WiFi: 75%"
      label_wifi_strength_100: "WiFi: 100%"  
    - type: "battery"
      label_draining: "{battery_level}--"
      label_power_saver: "{battery_level}--"
      label_charging: "{battery_level}++"
    - type: "tiling direction"
      label_horizontal: "⮂"
      label_vertical: "⮁"
      background: "#ffffff33"
      margin: "0 4px"
      padding: "0 8px"
    - type: "volume"
workspaces:
  - name: "1"
  - name: "2"
  - name: "3"

window_rules:
  # Floating system dialogs
  - command: "set floating"
    match_class_name: "#32770"

  # Fix Steam borders
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"

  # Windows ignores
  - command: "ignore"
    match_process_name: "/Taskmgr|ScreenClippingHost/"
  - command: "ignore"
    match_title: "[Pp]icture.in.[Pp]icture"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"

  # App ignores
  - command: "ignore"
    match_process_name: "regedit"
  - command: "ignore"
    match_process_name: "cs2"

binding_modes:
  # n/a
  
keybindings:
  # Shift focus
  - command: "focus left"
    binding: "Alt+H"
  - command: "focus right"
    binding: "Alt+L"
  - command: "focus up"
    binding: "Alt+K"
  - command: "focus down"
    binding: "Alt+J"

  # Move focused window
  - command: "move left"
    binding: "Alt+Shift+H"
  - command: "move right"
    binding: "Alt+Shift+L"
  - command: "move up"
    binding: "Alt+Shift+K"
  - command: "move down"
    binding: "Alt+Shift+J"

  # Resize focused window (% or px)
  - command: "resize width -5%"
    binding: "Alt+U"
  - command: "resize width +5%"
    binding: "Alt+P"
  - command: "resize height +5%"
    binding: "Alt+O"
  - command: "resize height -5%"
    binding: "Alt+I"
    
  # Tiling
  - command: "focus mode toggle"
    binding: "Alt+Space"
  - command: "toggle floating"
    binding: "Alt+Shift+Space"
  - command: "tiling direction toggle"
    binding: "Alt+V"

  # Minimize/maximize/close
  - command: "toggle maximized"
    binding: "Alt+Shift+M"
  - command: "set minimized"
    binding: "Alt+M"
  - command: "close"
    bindings: ["Alt+Q","Alt+Shift+Q"]

  # WM commands
  - command: "exit wm"
    binding: "Alt+Shift+E"
  - command: "reload config"
    binding: "Alt+Shift+R"
   
  # Focus workspace
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
    
  # Move to workspace
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Alt+Shift+3"

  # Windows execs
  - command: "exec wt"
    binding: "Alt+Enter"
  - command: "exec explorer"
    binding: "Alt+Shift+Enter"
  - command: "exec notepad"
    binding: "Alt+Shift+N"
  - command: "exec 'Z:/Peripherals + software/software/win/restartexplorer.bat'"
    binding: "Alt+R"
      
  # App execs 
  - command: "exec '%appdata%/Spotify/Spotify.exe'"
    binding: "Alt+S"
  - command: "exec '%programfiles%/Mozilla Firefox/firefox.exe'"
    binding: "Alt+F"
  - command: "exec '%programfiles%/Mozilla Firefox/private_browsing.exe'"
    binding: "Alt+N"
  - command: "exec '%programfiles(x86)%/Steam/steam.exe'"
    binding: "Alt+A"
  - command: "exec '%localappdata%/Discord/Discord'"
    binding: "Alt+D"
  - command: "exec '%programfiles(x86)%/ProtonVPN/ProtonVPN.exe'"
    binding: "Alt+Z"
